---
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/smatthaios/cloud-config
          username: smatthaios
          password: 123456!qqqqqq
          search-paths:
            - 'agora*'